import Head from 'next/head'
import Footer from '../components/Footer/Footer'

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Dawn Driving Tuition</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>homepage</h1>
    </>
  )
}
