import Masthead from '@/components/Masthead/Masthead'
import Head from 'next/head'
import Text from '@/components/Text/Text'
import ImagePartial from '@/components/Image/ImagePartial'

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Dawn Driving Tuition</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Masthead />
      <main className="container mt-5 mb-5">
        <div className="row flip">
          <div className="col-12 col-lg-6 ">
              <Text />
          </div>
          <div className="col-12 col-lg-6">
             <ImagePartial  />
          </div>
        </div>
      </main>
    </>
  )
}
